### PR TITLE
Support encoding plus char in path

### LINKED ISSUE #3653: Why do not encode ‘+’  in path?
What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/retrofit

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/6608b4713ad80988cdc9

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

## retrofit-v2.9.0

the api docs
https://github.com/square/retrofit/blob/7158698314daa138e993fac6a590ed19d78a8599/retrofit/src/main/java/retrofit2/http/Path.java#L48

```java
 @GET("/user/{name}")
 Call<ResponseBody> encoded(@Path("name") String name);

 @GET("/user/{name}")
 Call<ResponseBody> notEncoded(@Path(value="name", encoded=true) String name);
 
Calling foo.encoded("John+Doe") yields /user/John%2BDoe
whereas foo.notEncoded("John+Doe") yields /user/John+Doe.
```

https://github.com/square/retrofit/blob/fbf1225e28e2094bec35f587b8933748b705d167/retrofit/src/main/java/retrofit2/RequestBuilder.java#L133

```java
  private static String canonicalizeForPath(String input, boolean alreadyEncoded) {
    int codePoint;
    for (int i = 0, limit = input.length(); i < limit; i += Character.charCount(codePoint)) {
      codePoint = input.codePointAt(i);
      if (codePoint < 0x20
          || codePoint >= 0x7f
          || PATH_SEGMENT_ALWAYS_ENCODE_SET.indexOf(codePoint) != -1
          || (!alreadyEncoded && (codePoint == '/' || codePoint == '%'))) {
        // Slow path: the character at i requires encoding!
        Buffer out = new Buffer();
        out.writeUtf8(input, 0, i);
        canonicalizeForPath(out, input, i, limit, alreadyEncoded);
        return out.readUtf8();
      }
    }

    // Fast path: no characters required encoding.
    return input;
  }
```
The canonicalizeForPath method do not encode '+'

### PR DESCRIPTION
**Pull request by Goooler**
Closes #3653.

### CODE REVIEW

**Comment by JakeWharton** [comment]
https://github.com/square/retrofit/issues/3653#issuecomment-1911312533

**Comment by Goooler** [comment]
If so, may have to tweak
https://github.com/square/retrofit/blob/ee71a6858dfddcc4650f6ff4d71112911bdf6ca7/retrofit/src/main/java/retrofit2/http/Path.java#L52-L53

**Comment by JakeWharton** [comment]
Yeah the docs are probably from OkHttp 1.x days, or even before we used OkHttp.

**Comment by Zhuinden** [comment]
This bug is causing quite a bit of headache now in 2025. 

Retrofit claims to be URL-encoding parameters, but it refuses to do it for `+` in a path parameter, even though according to URL-encode specification, it should be encoded. Unfortunate for me because it makes my situation a little tricky. 😅

**Pull request closed without merging**
