### PR TITLE
Test all Rx types can be subscribed to twice

### PR DESCRIPTION
**Pull request by JakeWharton**

### CODE REVIEW

**Comment by swankjesse** [comment]
The consequences of this are interesting. Not subscribing at all will make zero network requests!

**Comment by JakeWharton** [comment]
Yep. Same as a Call though. Only things like coroutines and futures trigger when you invoke the method. The distinction should be documented on the call adapters.

**Comment by oldergod** [comment]
> Not subscribing at all will make zero network requests!

Hasn't that been the case before? Did something change recently?

**Comment by JakeWharton** [comment]
Nope. Always been the case.

**Pull request merged**
