### PR TITLE
Ban star imports

### PR DESCRIPTION
**Pull request by JakeWharton**
I don't know why GJF doesn't at least fail on these, but whatever EP to the rescue. Editor config still seems to be allowing IntelliJ to create these, though. Future problem.

### CODE REVIEW

**Comment by Goooler** [comment]
And we can add rules:

```editorconfig
ij_java_class_count_to_use_import_on_demand = 999
ij_kotlin_name_count_to_use_star_import = 999
ij_kotlin_name_count_to_use_star_import_for_members = 999
```

**Comment by JakeWharton** [comment]
Oh I thought I sent those. I have a bunch on a branch somewhere. Still have to figure out the minimal set to fix the import order to agree with GJF.

**Comment by Goooler** [comment]
If we can add an option in Spotless JavaExtension?

**Comment by JakeWharton** [comment]
I'd prefer it be in the editorconfig if possible

**Pull request merged**
