### PR TITLE
Added RxJava3 adapter

### LINKED ISSUE #3297: First-party RxJava 3 adapter

### PR DESCRIPTION
**Pull request by mickverm**
Closes #3297

### CODE REVIEW

**Comment by provJoshMieczkowski** [comment]
@mickverm you have some failing tests

**Comment by mickverm** [comment]
The following tests fail:

**FlowableTest**
- responseRespectsBackPressure
- bodyRespectsBackpressure
- resultRespectsBackpressure

All with the same reason:

```
org.junit.ComparisonFailure: 
Expected :1
Actual      :0
```

I noticed these same tests from the adapter-rxjava2 succeed but not without throwing errors:

```
Feb 26, 2020 7:19:13 PM okhttp3.mockwebserver.MockWebServer$3 execute
INFO: MockWebServer[52498] starting to accept connections
java.lang.IllegalArgumentException: n > 0 required but it was 0
	at io.reactivex.internal.subscriptions.SubscriptionHelper.validate(SubscriptionHelper.java:80)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.request(FlowableOnBackpressureLatest.java:85)
	at retrofit2.adapter.rxjava2.RecordingSubscriber.onSubscribe(RecordingSubscriber.java:45)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.onSubscribe(FlowableOnBackpressureLatest.java:59)
	at io.reactivex.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.onSubscribe(FlowableFromObservable.java:60)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onSubscribe(BodyObservable.java:46)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:38)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at io.reactivex.internal.operators.flowable.FlowableFromObservable.subscribeActual(FlowableFromObservable.java:31)
	at io.reactivex.Flowable.subscribe(Flowable.java:12172)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest.subscribeActual(FlowableOnBackpressureLatest.java:31)
	at io.reactivex.Flowable.subscribe(Flowable.java:12172)
	at retrofit2.adapter.rxjava2.FlowableTest.bodyRespectsBackpressure(FlowableTest.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at retrofit2.adapter.rxjava2.RecordingSubscriber$Rule$1.evaluate(RecordingSubscriber.java:146)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Exception in thread "main" java.lang.IllegalArgumentException: n > 0 required but it was 0
	at io.reactivex.internal.subscriptions.SubscriptionHelper.validate(SubscriptionHelper.java:80)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.request(FlowableOnBackpressureLatest.java:85)
	at retrofit2.adapter.rxjava2.RecordingSubscriber.onSubscribe(RecordingSubscriber.java:45)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.onSubscribe(FlowableOnBackpressureLatest.java:59)
	at io.reactivex.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.onSubscribe(FlowableFromObservable.java:60)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onSubscribe(BodyObservable.java:46)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:38)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
	at io.reactivex.Observable.subscribe(Observable.java:10151)
	at io.reactivex.internal.operators.flowable.FlowableFromObservable.subscribeActual(FlowableFromObservable.java:31)
	at io.reactivex.Flowable.subscribe(Flowable.java:12172)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest.subscribeActual(FlowableOnBackpressureLatest.java:31)
	at io.reactivex.Flowable.subscribe(Flowable.java:12172)
	at retrofit2.adapter.rxjava2.FlowableTest.bodyRespectsBackpressure(FlowableTest.java:84)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at retrofit2.adapter.rxjava2.RecordingSubscriber$Rule$1.evaluate(RecordingSubscriber.java:146)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Feb 26, 2020 7:19:13 PM okhttp3.mockwebserver.MockWebServer$4 processOneRequest
INFO: MockWebServer[52498] received request: GET / HTTP/1.1 and responded: HTTP/1.1 200 OK
Feb 26, 2020 7:19:13 PM okhttp3.mockwebserver.MockWebServer$3 acceptConnections
INFO: MockWebServer[52498] done accepting connections: Interrupted function call: accept failed

```

**Comment by provJoshMieczkowski** [comment]
I'm looking into atm and I've noticed that in `CallExecuteObservable` for the rxjava3 adapter, this guy `if (disposable.isDisposed())` is returning true which is why the test are failing but if you look at the rxjava2 version, that is returning false and allow the data to continue.

**Comment by provJoshMieczkowski** [comment]
@mickverm is removing the tests the right solution vs figuring out why `CallExecuteObservable` is being disposable as soon as we use it?

**Comment by provJoshMieczkowski** [comment]
Doing some more digging, I've noticed that in `RecordingSubscriber` we are calling `subscription.request(initialRequest);` with `initialRequest` = 0. That causes an error to be thrown at `StrictSubscriber.request` because 0 is not a valid value

**Comment by provJoshMieczkowski** [comment]
Ok, I have found the issue. In `Flowable.subscribe` if you do not pass in a `FlowableSubscriber` (the `RecordingSubscriber` was using just Subscriber), it will default to using a `StrictSubscriber` which caused the tests to fail.

**Comment by provJoshMieczkowski** [comment]
https://github.com/mickverm/retrofit/pull/1
@mickverm open a PR on your fork that fixes the tests 👍

**Comment by mickverm** [comment]
> [mickverm#1](https://github.com/mickverm/retrofit/pull/1)
> @mickverm open a PR on your fork that fixes the tests 👍

You're right, I've implemented your changes.

**Comment by mutunenthaby** [comment]
African customary Healer botanist arranged in South Africa and significant Marriage counselor and diviner Call/Whatsapp +27670093205 or Email mamawata85@gmail.com

• Bringing back lost darlings in a 72 hours 

• Divorce or Court issues 

• Financial issues and DEBTS 

• Preventing your accessory from undermining you 

• Making your accessory love just you 

• Get a separation settlement quickly from your ex-accessory 

• Removal of misfortune 

• Buy a house or vehicle of your dream 

• I help understudies with completing their tests/interviews 

• I help those searching for work 

• Speed up money ensure spell delayed, payments, pension and incident stores 

• Unfinished occupations by various masters if not satisfied come to me. 

• Win business tenders and understandings 

• Do you need to recover your lost property 

• Promotion busy working and better pay. 

• Do you should be protected from awful spirits terrible dreams? 

• Are you a priest, administrator, botanist who needs to get more powers? 

• Why you can't keep money or sweethearts? 

• Why you have a lot of adversaries? 

• Why you are fired routinely on jobs?

**Comment by provJoshMieczkowski** [comment]
Is anyone looking at this guy? Would be awesome if we can merge it in so we can upgrade RxJava :D

**Comment by AdamSHurwitz** [comment]
@akarnokd has created a library for the `rxjava3-retrofit-adapter`. See this [StackOverflow post](https://stackoverflow.com/a/45075878/2253682) for details. 

`implementation "com.github.akarnokd:rxjava3-retrofit-adapter:3.0.0"`

**Comment by JakeWharton** [comment]
Updated some docs and change the default behavior to async.

**Pull request merged**
