### PR TITLE
Build with Gradle

### PR DESCRIPTION
**Pull request by larsgrefer**
I've just tried if its possible to move from maven to gradle and it works.

Here are the results

### CODE REVIEW

**Comment by JakeWharton** [comment]
What's the value proposition of switching? Having used both build system extensively, I cannot think of any.

**Comment by larsgrefer** [comment]
I can't think of any, too (except that gradle is much cooler :stuck_out_tongue_closed_eyes:), but if someone wants to move to gradle someday: here is how.

**Comment by JakeWharton** [comment]
At this time, Maven is a much easier build system to use for managing open source projects. The release process, CI process, and IDE integration are all superior to Gradle. Without some additional value to offset the fact that Gradle is worse at these things, I don't see any reason to switch at this time.

**Comment by JakeWharton** [comment]
I appreciate you putting in the work, but for something so drastic please create an issue ahead of time that we can potentially save you some effort or direct it towards something we know will be integrated.

**Pull request closed without merging**
