### PR TITLE
Rename LICENSE.txt to LICENSE

### PR DESCRIPTION
**Pull request by SUPERCILEX**
This is the new default for GitHub and looks much nicer.

### CODE REVIEW

**Comment by JakeWharton** [comment]
This would probably be annoying for Windows users. Even disregarding that, I see no reason for the change.

**Comment by SUPERCILEX** [comment]
@JakeWharton Since GitHub uses `LICENSE` by default, license displayer libraries are going to make that their default. As for it being annoying for Windows users, who reads the license anyway? I doubt that will much of an issue. However, it makes it easier for license libraries if you follow the GitHub default.

**Comment by JakeWharton** [comment]
No license checker of any quality would omit checking for a .txt version.

**Comment by SUPERCILEX** [comment]
Of course not, but they would start by checking for GitHub's default and
then the .txt version. Heck, even you use the non .txt version for some of
your repos: [
https://github.com/ReactiveX/RxAndroid/blob/2.x/**LICENSE**](https://github.com/ReactiveX/RxAndroid/blob/2.x/LICENSE)
.

**Comment by JakeWharton** [comment]
I didn't create that repo

**Comment by SUPERCILEX** [comment]
@JakeWharton Yeah, but you maintain it.

@JakeWharton Fine, I tried. I created https://github.com/yshrsmz/LicenseAdapter/pull/22 anyway to fix this problem so it's good, I guess. I still prefer `LICENSE` instead of `LICENSE.txt`. 😄

**Pull request closed without merging**
