### PR TITLE
Greeno/extend interface option

### PR DESCRIPTION
**Pull request by greeno**
Addresses issue in https://github.com/square/retrofit/issues/504

### CODE REVIEW

**Comment by podollb** [comment]
This would be great!

**Comment by Nthalk** [comment]
Agreed! I have a large api that I was hoping to use this for, and the lack of composable interfaces make this a deal breaker for me!

**Comment by JakeWharton** [comment]
@Nthalk Retrofit favors composition. This PR adds inheritance.

**Comment by Nthalk** [comment]
We are talking about interfaces here. Especially a situation where the body methods are provided by a declarative convention.

I find it hard to imagine that any of the inheritance vs composition pitfalls are here.

Also, because of the requirement that the source must be an interface, this also precludes delegation at the definition.

Do you really have a single adapter with a ton of proxies?

**Comment by JakeWharton** [comment]
Yes. They are generated from a service declaration in protos. One interface per service.

**Comment by carek** [comment]
In my opinion this validation breaks Single Responsible Principal. Could you please reconsider this? :)

**Comment by swankjesse** [comment]
I don't think this is a good fit for Retrofit's API.

**Comment by ashneo76** [comment]
What is the reason for closing this PR without even explaining a possible solution using your proposed approach?

**Comment by kennymacleod** [comment]
Please reconsider this.

My use case is that I have an interface that defines a set of operations without any Retrofit annotations. This interface is agnostic to the remoting layer. I then have two extensions of this interface, which annotates the methods with either Retrofit or RemotingTechnologyX.

Retrofit currently forbids this, for no reason other than composition should be encouraged over inheritance. While I agree with the principle, enforcing it like this is a blunt hammer than ignores the perfectly valid use cases for using interface inheritance.

**Comment by JakeWharton** [comment]
And, you know, the fact that it doesn't work on some versions of Android.

**Pull request closed without merging**
