### PR TITLE
Added OPTIONS to the built-in methods

### PR DESCRIPTION
**Pull request by avbk**
Hey guys,

first of all, thanks for the great work. 
We are currently working on a project, which heavily uses the OPTIONS method. I did not read about the @HTTP annotation (just saw it when adding the docs and the test; darn). So I forked the project and added the @OPTIONS annotation. 
Since there is the @HTTP annotation, this might not be that useful, but maybe you still like to add it to your codebase.

Best regards
Alex

### CODE REVIEW

**Comment by JakeWharton** [comment]
Does your project return a body in the OPTIONS response?

**Comment by jkwiecien** [comment]
We could use @OPTIONS aswell :)

**Comment by RoyMontoya** [comment]
i think it could work fine as optional annotation, but it could also be confusing for the users because its pretty much the same as @HTTP

**Comment by damianflannery** [comment]
+1 for OPTIONS

**Comment by avbk** [comment]
@JakeWharton sorry for the late answer. Yes, we do have a body specifying allowed values for the API for example.

**Comment by JakeWharton** [comment]
Fixed, squashed, and merged. Thanks!

**Pull request closed without merging**
