### PR TITLE
proguard update

### PR DESCRIPTION
**Pull request by RicardoBravoA**
Doesn't allow generate an apk when using proguard
- Warning:there were 14 unresolved references to classes or interfaces.
- Warning:Exception while processing task java.io.IOException: Please correct the above warnings first.
- Error:Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> java.io.IOException: Please correct the above warnings first.

### CODE REVIEW

**Comment by Jawnnypoo** [comment]
I think since this is actually a ProGuard issue with Okio, it should if anything be a note or a link below the actual proguard configuration, to differentiate.

**Comment by JakeWharton** [comment]
It's not really an issue, but yes it's for Okio and not Retrofit directly.
We should document the Okio rules and just link to them. I do not want them
duplicated.

**Comment by Jawnnypoo** [comment]
Would you like me to make a PR on Okio? Or are you on it?

**Comment by JakeWharton** [comment]
See #2119

**Pull request closed without merging**
