### PR TITLE
Add optional headers to @Part annotation

### PR DESCRIPTION
**Pull request by iagreen**
Add a `headers` property to the `Part` annotation to allow for custom headers inside each part of the multipart body.

Inspired by this [SO question](http://stackoverflow.com/q/41164123/1904517).

### CODE REVIEW

**Comment by JakeWharton** [comment]
Honestly I'm really hesitant about exposing this as an API. Can you talk about your specific use case more? I'm tempted to say that you should just use a `MultipartBody.Part` as the type which allows specifying custom headers in the runtime instance and not the compile-time Retrofit annotations.

**Comment by anninos** [comment]
So how can you pass/set custom headers to a part?

**Comment by iagreen** [comment]
@JakeWharton This totally fell of my radar, but I agree with you.  It is probably better to build the `Part` than annotate it.

**Comment by anninos** [comment]
Because I am not really sure what you mean by that, can you give me an example or something?

**Pull request closed without merging**
