### PR TITLE
support fastjson,add converter-fastjson.Thanks

### PR DESCRIPTION
**Pull request by why168**
Excuse me,JakeWharton.request support fastjson.please review code.Because We use this framework a lot in China.Thanks

### CODE REVIEW

**Comment by why168** [comment]
```java
public class FastJsonConverterFactory
final class FastJsonRequestBodyConverte
final class FastJsonResponseBodyConverter
public class FastJsonConverterFactoryTest
```

```groovy
implementation 'com.squareup.retrofit2:converter-fastjson:latest.version'
```

**Comment by ytRino** [comment]
New first party converters are rarely added. https://github.com/square/retrofit/pull/1943

**Comment by why168** [comment]
> 很少添加新的第一方转换器。[＃1943年](https://github.com/square/retrofit/pull/1943)

👌

**Comment by JakeWharton** [comment]
We are not taking on any new first-party converters at this time. There are already two fastjson converters listed on https://github.com/square/retrofit/wiki/Converters, and you're free to release yours as a standalone library and update the wiki page.

**Pull request closed without merging**
