### PR TITLE
Add a JAXB 3 converter

### LINKED ISSUE #3536: Retrofit JAXB Converter does not work with Jakarta JAXB
Not sure if it is a bug report or feature request. In my recent project I have both old java.xml.bind and jakarta.xml.bind implementations are on classpath. My classes are annotated with jakarta.xml.bind.*. I am getting following error

 ```
java.lang.IllegalArgumentException: Unable to create @Body converter for class com.sil.upi.jaxb.RespListAccount (parameter #3)
    for method UPIService.sendRespListAccount
        at retrofit2.Utils.methodError(Utils.java:54)
        at retrofit2.Utils.parameterError(Utils.java:60)
        at retrofit2.RequestFactory$Builder.parseParameterAnnotation(RequestFactory.java:781)
        at retrofit2.RequestFactory$Builder.parseParameter(RequestFactory.java:325)
        at retrofit2.RequestFactory$Builder.build(RequestFactory.java:206)
        at retrofit2.RequestFactory.parseAnnotations(RequestFactory.java:67)
        at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:26)
        at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
        at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
        at com.sun.proxy.$Proxy78.sendRespListAccount(Unknown Source)
        at com.sil.upi.application.RetroClient.sendRespListAccount(RetroClient.java:101)
        at com.sil.upi.services.meta.ListAccount.run(ListAccount.java:110)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.IllegalArgumentException: Could not locate RequestBody converter for class com.sil.upi.jaxb.RespListAccount.
  Tried:
   * retrofit2.BuiltInConverters
   * retrofit2.converter.jaxb.JaxbConverterFactory
   * retrofit2.OptionalConverterFactory
        at retrofit2.Retrofit.nextRequestBodyConverter(Retrofit.java:335)
        at retrofit2.Retrofit.requestBodyConverter(Retrofit.java:293)
        at retrofit2.RequestFactory$Builder.parseParameterAnnotation(RequestFactory.java:778)
        ... 12 more
```

I can understand retrofit jaxb converter is compiled with java.xml.bind so I am getting error on deserialization. Is there a possibility that future converter release will work for both implementations?

### PR DESCRIPTION
**Pull request by mrook**
This PR adds a converter that uses JAXB 3.0.1 and `jakarta.xml.bind` instead of `java.xml.bind`. I've called the module `converter-jaxb3` as I'm sure people will want to retain the other JAXB converter.

Let me know what you think. CLA has been signed in any case.

This should resolve #3536.

### CODE REVIEW

**Comment by JakeWharton** [comment]
Thanks! On a 10-second scroll-by it looks good. I won't be able to properly review until next week. Just wanted to acknowledge the PR, though.

**Comment by mrook** [comment]
No worries! It's mostly a straight copy of the existing converter, with the dependencies / imports changed.

**Comment by KrishnaST** [comment]
any updates?

**Comment by bmmule** [comment]
is it released yet.

**Comment by KrishnaST** [comment]
why it is not released yet?

**Comment by bentatham** [comment]
Currently, we are migrating from javax->jakarta namespace, and have to depend on the 2.10.0-SNAPSHOT of retrofit to pick this up.  

Anything I can do to help to get retrofit released?  I'm happy to help out.

**Comment by tyilo** [comment]
It has now been almost 2 years since this was merged. When can we expect a release?

**Comment by yesitskev** [comment]
@JakeWharton is there a release timeline for this artifact?

**Comment by tyilo** [comment]
Seems to actually have been released now :tada:

https://central.sonatype.com/artifact/com.squareup.retrofit2/converter-jaxb3/versions

**Pull request merged**
