### PR TITLE
moved validation first before cloning

### PR DESCRIPTION
**Pull request by guptasourabh**
First Validate the TypeArguments and then do the cloning of that.

### CODE REVIEW

**Comment by guptasourabh** [comment]
@JakeWharton please do the review

**Comment by jaredsburrows** [comment]
LGTM. That's a good idea.

**Comment by guptasourabh** [comment]
@JakeWharton please check the PR.

**Comment by JakeWharton** [comment]
On vacation

**Comment by JakeWharton** [comment]
Rarely is there value in optimizing a code path that results in an exception because the overhead of creating and throwing the exception will dwarf any small change like this.

**Pull request merged**
