### PR TITLE
Do not proxy default methods on service interfaces.

### LINKED ISSUE #998: Do not modify default interface methods (just ignore them)
Currently the following exception is thrown when default interface methods a used:

    java.lang.IllegalArgumentException: MyService.load: HTTP method annotation is required (e.g., @GET, @POST, etc.).

Found while trying to workaround  #997 

    @GET(..)
    Response load( 
         @Query("a") Integer a,
         @Query("b") Integer b
    );

    default Response simpleLoad(Request r 
         return load(
                  r.getA(),
                  r.getB()
         );
    );

### PR DESCRIPTION
**Pull request by JakeWharton**
Closes #998.

This is not easily testable, and I'm not in the mood to craft Java 8 integration tests.

### CODE REVIEW

**Comment by JakeWharton** [comment]
Can't compile with JDK 7 with this change. Not sure how I feel about that.

**Comment by swankjesse** [comment]
LGTM. If you want to require Java 8 for building, we'll want to add animal sniffer.

**Comment by swankjesse** [comment]
(eventually!)

**Comment by JakeWharton** [comment]
Added animal sniffer.

**Pull request merged**
