### PR TITLE
Remove specialized ConversionException.

### PR DESCRIPTION
**Pull request by JakeWharton**
Prefer normal IOExceptions or any RuntimeException for unexpected things.

### CODE REVIEW

**Comment by JakeWharton** [comment]
@swankjesse @adriancole 

Got a biggun' lined up after this guy!

**Comment by JakeWharton** [comment]
Actually, TBR. I'm sick of rebasing :)

**Comment by swankjesse** [comment]
LGTM

**Comment by adriancole** [comment]
Late LGTM

**Pull request merged**
