### PR TITLE
BOM publishing

### PR DESCRIPTION
**Pull request by realdadfish**
Alternative to #3487

### CODE REVIEW

**Review by Mita1w — APPROVED** [review]

**Comment by realdadfish** [comment]
Shall I rebase to resolve the conflicts? Is there an interest to get this merge-ready?

**Comment by madorb** [comment]
well, i for one, would love to see it

**Comment by Mita1w** [comment]
Yep me to

**Comment by realdadfish** [comment]
@Mita1w Rebased, please have a look.

**Review by Goooler — APPROVED** [review]

**Pull request closed without merging**
